version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - cd src
      - zip -r9 ../src.zip .
      - cd ..
      - zip -g deployment_package.zip src.zip lambda_function.py
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name ibb_func_test --zip-file fileb://deployment_package.zip
      - echo "DONE!"