version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -ur deployment_package.zip lib src lambda_function.py
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name ibb_func_test --zip-file fileb://deployment_package.zip
      - echo "DONE"